expenses_tracker/expenses_tracker/expenses_app/urls.py
from django.urls import path

from expenses_tracker.expenses_app.views import index, profile, edit_profile, delete_profile, create_expense, \
    edit_expense, delete_expense

urlpatterns = [
    path('', index, name='index'),
    path('profile/', profile, name='profile'),
    path('profile/edit/', edit_profile, name='edit_profile'),
    path('profile/delete/', delete_profile, name='delete_profile'),
    path('create/', create_expense, name='create_expense'),
    path('edit/<int:pk>', edit_expense, name='edit_expense'),
    path('delete/<int:pk>', delete_expense, name='delete_expense'),
]

expenses_tracker/expenses_tracker/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('expenses_tracker.expenses_app.urls')),
]   + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

expenses_tracker/expenses_tracker/expenses_app/models.py
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator, MinLengthValidator
from django.db import models


# Create your models here.
from django.utils.deconstruct import deconstructible


def validate_only_letters(value):
    if not value.isalpha():
        raise ValidationError('Ensure this value contains only letters.')

# @deconstructible
# def MaxFileSizeInMBValidator:
#     def __init__(self, max_size):
#         self.max_size = max_size
#
#     def __call__(self, value):
#         filesize = value.file.size
#         if filesize > self.max_size * 1024 * 1024:
#             raise ValidationError('Max file size is 5.00 MB')


class Profile(models.Model):
    IMAGE_MAX_SIZE = 5

    first_name = models.CharField(
        max_length=15,
        validators=(
            MinLengthValidator(2),
            validate_only_letters,
        )
    )
    last_name = models.CharField(
        max_length=15,
        validators=(
            MinLengthValidator(2),
            validate_only_letters,
        )
    )
    budget = models.IntegerField(
        default=0,
        validators=(
            MinValueValidator(0),
        ),
    )
    image = models.ImageField(
        upload_to='profiles/',
        null=True,
        blank=True,
        # validators=(
        #     MaxFileSizeInMBValidator(IMAGE_MAX_SIZE),
        # )
    )


class Expense(models.Model):
    title = models.CharField(
        max_length=50
    )
    image_url = models.URLField()
    description = models.TextField(
        null=True,
        blank=True,
    )
    price = models.FloatField()

expenses_tracker/expenses_tracker/expenses_app/forms.py
from django import forms

from expenses_tracker.expenses_app.models import Profile, Expense


class BootstrapFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._init_bootstrap_fields()

    def _init_bootstrap_fields(self):
        for (_, field) in self.fields.items():
            if 'class' not in field.widget.attrs:
                field.widget.attrs['class'] = ''
            field.widget.attrs['class'] += 'form-control'


class ProfileForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'


class ExpenseForm(BootstrapFormMixin, forms.ModelForm):
    class Meta:
        model = Expense
        fields = '__all__'


class DeleteExpenseForm(ExpenseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for (_, field) in self.fields.items():
            # field.widget.attrs['readonly'] = 'readonly'
            field.widget.attrs['disabled'] = 'disabled'

expenses_tracker/expenses_tracker/expenses_app/views.py
from django.shortcuts import render, redirect

# Create your views here.
from expenses_tracker.expenses_app.forms import ProfileForm, ExpenseForm, DeleteExpenseForm
from expenses_tracker.expenses_app.models import Profile, Expense

def money_left():
    expenses = Expense.objects.all()
    budget = Profile.objects.all().first().budget
    if expenses:
        for expense in expenses:
            budget -= expense.price
        return budget

def index(request):
    person = Profile.objects.all().first()
    if request.method == 'GET':
        if person:
            expenses = Expense.objects.all()
            #if expenses:
            budget_left = money_left()
            context = {
                'person': person,
                'expenses': expenses,
                'budget_left': budget_left,
            }
            return render(request, 'home-with-profile.html', context)
            # else:
            #     context = {
            #         'person': person,
            #     }
            #     return render(request, 'home-with-profile.html', context)

        else:
            return render(request, 'home-no-profile.html')
    else:
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            expenses = Expense.objects.all().first()
            if not expenses:
                return render(request, 'home-with-profile.html')
            else:
                context = {
                    'expenses': expenses
                }
                return render(request, 'home-with-profile.html', context)


def profile(request):
    person = Profile.objects.all().first()
    budget_left = money_left()
    if request.method == 'GET':
        if person:
            context = {
                'person': person,
                'budget_left': budget_left
            }
            return render(request, 'profile.html', context)


# def edit_profile(request, pk):
#     person = Profile.objects.get(pk=pk)
#     if request.method == 'POST':
#         form = ProfileForm(request.POST, instance=person)
#         if form.is_valid():
#             form.save()
#             return redirect('index')
#         else:
#             context = {
#                 'form': form
#             }
#             return render(request, 'profile-edit.html', context)
#     else:
#         form = ProfileForm(initial=person.__dict__)
#         # form = ProfileForm(instance=person)
#         context = {
#             'form': form,
#         }
#         return render(request, 'profile-edit.html', context)
def edit_profile(request):
    person = Profile.objects.all().first()
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=person)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            context = {
                'form': form
            }
            return render(request, 'profile-edit.html', context)
    else:
        form = ProfileForm(initial=person.__dict__)
        # form = ProfileForm(instance=person)
        context = {
            'form': form,
        }
        return render(request, 'profile-edit.html', context)


def delete_profile(request):
    person = Profile.objects.all().first()
    if request.method == 'POST':
        # expenses = Expense.objects.all()
        # if expenses:
        #     for expense in expenses:
        #         expense.delete()
        ## A better way to delete the expenses:
        Expense.objects.all().delete()
        person.delete()
        return redirect('index')
    else:
        return render(request, 'profile-delete.html')


def create_expense(request):
    if request.method == 'POST':
        form = ExpenseForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            context = {
                'form': form
            }
            return render(request, 'expense-create.html', context)
    else:
        form = ExpenseForm()
        context = {
            'form': form
        }
        return render(request, 'expense-create.html', context)


def edit_expense(request, pk):
    expense = Expense.objects.get(pk=pk)
    if request.method == 'POST':
        form = ExpenseForm(request.POST, instance=expense)
        if form.is_valid():
            form.save()
            return redirect('index')
        else:
            context = {
                'form': form
            }
            return render(request, 'expense-create.html', context)
    else:
        form = ExpenseForm(initial=expense.__dict__)
        context = {
            'form': form,
        }
        return render(request, 'expense-edit.html', context)


def delete_expense(request, pk):
    expense = Expense.objects.get(pk=pk)
    if request.method == 'POST':
        expense.delete()
        return redirect('index')
    else:
        expense = DeleteExpenseForm(initial=expense.__dict__)
        context = {
            'expense': expense,
        }
        return render(request, 'expense-delete.html', context)

expenses_tracker/templates/expense-create.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Create Expense</h1>
<div class="form">
    <form method="POST">
{#        <input type="hidden" name="csrfmiddlewaretoken" value="HUrRfZ1Xv8I1kg0RCRhg5I8sTJMRfcaLEI9Pf4LGjQXUjsQgoxLnWAleb0K01njw">#}
        {% csrf_token %}
        <label for="name">Title</label>
        <input type="text" name="title" maxlength="50" required="" id="id_title">

        <label for="description">Description</label>
        <textarea name="description" cols="40" rows="10" required="" id="id_description"></textarea>

        <label for="imageUrl">Link to Image</label>
        <input type="url" name="image_url" maxlength="200" required="" id="id_image_url">

        <label for="price">Price</label>
        <input type="number" name="price" step="any" required="" id="id_price">

        <input type="submit" value="Create">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/expense-delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Delete Expense</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="hwapnt8nZjnQuJ2M6SZBuXGgOwc3fZlrekSnnyS6N1CJtVSbSytIlPT26Nac1auc">
        {% csrf_token %}
        <label for="name">Title</label>
{#        <input type="text" name="title" value="Electrical Piano" maxlength="50" disabled="" required="" id="id_title">#}
        {{ expense.title }}

        <label for="description">Description</label>
{#        <textarea name="description" cols="40" rows="10" disabled="" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>#}
        {{ expense.description }}

        <label for="image_url">Link to Image</label>
{#        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" disabled="" required="" id="id_image_url">#}
        {{ expense.image_url }}


        <label for="price">Price</label>
{#        <input type="number" name="price" value="1000.0" step="any" disabled="" required="" id="id_price">#}
        {{ expense.price }}

        <input type="submit" value="Delete">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/expense-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a href="/profile">Profile</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Edit Expense</h1>
<div class="form">
    <form method="POST">
        <input type="hidden" name="csrfmiddlewaretoken" value="E8qoLvlyiXBfE7NlcyWlXe1TMWV5qvo7BW8mLA5h6FQ8DjDKYeqsO6eF4dTecGxS">
        {% csrf_token %}
        <label for="name">Title</label>
{#        <input type="text" name="title" value="Electrical Piano" maxlength="50" required="" id="id_title">#}
        {{ form.title }}

        <label for="description">Description</label>
{#        <textarea name="description" cols="40" rows="10" required="" id="id_description">I bought myself a new piano to improve my skills</textarea>#}
        {{ form.description }}

        <label for="image_url">Link to Image</label>
{#        <input type="url" name="image_url" value="https://www.pngkit.com/png/full/307-3075914_free-piano-clipart-piano-png.png" maxlength="200" required="" id="id_image_url">#}
        {{ form.image_url }}

        <label for="price">Price</label>
{#        <input type="number" name="price" value="1000.0" step="any" required="" id="id_price">#}
        {{ form.price }}

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/home-no-profile.html
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="./static/css/style.css">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
    </ul>
</nav>
    <div class="body">
        
<h1>Enter your data</h1>
<div class="form">
    <form method="POST">
{#        <input type="hidden" name="csrfmiddlewaretoken" value="97MmAxmrs7yPXUamEdIgRY80OHEP383f6VukAC6agPNIW60LqTcnIQlM6YCYPjc0">#}
        {% csrf_token %}
        <label for="budget">Budget</label>
        <input type="number" name="budget" required="" id="id_budget">

        <label for="firstName">First Name</label>
        <input type="text" name="first_name" maxlength="15" required="" id="id_first_name">

        <label for="lastName">Last Name</label>
        <input type="text" name="last_name" maxlength="15" required="" id="id_last_name">

        <input type="submit" value="Submit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/home-with-profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="./static/images/dollar.png"></li>
        <li><a href="/">Expenses Tracker</a></li>
        
        <li class="right"><a class="button" href="/profile">Profile</a></li>
        
    </ul>
</nav>

<div class="body">
{% if expenses %}
<div>
    <h1>Summary</h1>
<h1>
    <ul class="expenses-list">
    <li class="blue">{{ person.budget|floatformat:2 }}$</li>
    {% for expense in expenses %}
        <li class="red"> - {{ expense.price|floatformat:2 }}$</li>
    {% endfor %}
    
    <li class="green">= {{ budget_left }}$ left</li>
    </ul>
</h1></div>
{% endif %}
</div>

<div>
<h1>My Expenses</h1>

    <li class="button"> <a href="{% url 'create_expense' %}">Add Expensе</a></li>

{#<div>#}
{#    <a class="button edit" href="{% url 'create_expense' %}">Add Expense</a>#}
</div>


{% if expenses %}
        {% for expense in expenses %}
            <div class="expense-container">
                <h2>{{ expense.title }}</h2>
{#                <hr>#}
                <img src="{{ expense.image_url }}" alt="нема го">
                <p>{{ expense.description}}</p>
                <div class="expense-detail">
                    <div>
                        <p>Price: {{ expense.price }}$</p>
                    </div>
                    <div class="right">
                        <a class="button edit" href="/edit/{{ expense.id }}">Edit</a>
                        <a class="button delete" href="/delete/{{ expense.id }}">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
{% endif %}




<footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/profile-delete.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
{#<nav>#}
{#    <ul>#}
{#        <li class="img"><img src="./static/images/dollar.png"></li>#}
{#        <li><a href="/">Expenses Tracker</a></li>#}
{#        #}
{#        <li class="right"><a href="/profile">Profile</a></li>#}
{#        #}
{#    </ul>#}
{#</nav>#}
    <div class="body">
        
<h1>Are you sure you want to delete your profile?</h1>
<form method="POST">
<input type="hidden" name="csrfmiddlewaretoken" value="fewGdgFCGlbXTIgYQJKFmURDSd5iqPnic2eEdlplu3qQSU6nCpeMdM4pau3rc0w3">
{% csrf_token %}
<button class="delete">Confirm</button>
</form>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/profile-edit.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
{#<nav>#}
{#    <ul>#}
{#        <li class="img"><img src="./static/images/dollar.png"></li>#}
{#        <li><a href="/">Expenses Tracker</a></li>#}
{#        #}
{#        <li class="right"><a href="/profile">Profile</a></li>#}
{#        #}
{#    </ul>#}
{#</nav>#}
{#    <div class="body">#}
        
<h1>Enter your new data</h1>
<div class="form">
    <form method="POST" enctype="multipart/form-data">
{#        <input type="hidden" name="csrfmiddlewaretoken" value="M6BlBJtidtTAjIVkeKKrO0pzGsJVBeMuJUjjBOd11b8tiULJ0qeyFSClYJH4npVf">#}
        {% csrf_token %}
        <label for="budget">Budget</label>
{#        <input type="number" name="budget" value="{{ person.budget }}" required="" id="{{ person.budget }}">#}
        {{ form.budget }}

        <label for="firstName">First Name</label>
{#        <input type="text" name="first_name" value="Tanya" maxlength="15" required="" id="id_first_name">#}
        {{ form.first_name }}

        <label for="lastName">Last Name</label>
{#        <input type="text" name="last_name" value="Staneva" maxlength="15" required="" id="id_last_name">#}
        {{ form.last_name }}

        {{ form.image }}

        <input type="submit" value="Edit">
    </form>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>

expenses_tracker/templates/profile.html
{% load static %}
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <title>Expenses Tracker</title>
</head>

<body>
    
<nav>
    <ul>
        <li class="img"><img src="{% static 'images/dollar.png' %}"></li>
        <li><a href="/">Expenses Tracker</a></li>

        <li class="right"><a href="/profile">Profile</a></li>

    </ul>
</nav>
    <div class="body">
        
<h1>Your Profile</h1>
<div class="expenses-container">
    <div class="expense-container">
        <h2>{{ person.first_name }} {{ person.last_name}}</h2>
        <hr>
{#        <img src="{% static 'images/user.png' %}">#}
        <img src="{{ person.image.url }}">
        <p>In your profile you can edit your profile data</p>
        <div class="expense-detail">
            <div>
                <p>Budget Left: {{ budget_left }}$</p>
            </div>
            <div class="right">
                <a class="button edit" href="{% url 'edit_profile' %}">Edit Profile</a>
                <a class="button delete" href="/profile/delete">Delete Profile</a>
            </div>
        </div>
    </div>
</div>

    </div>
    <footer>
    <div>Python Web Basics Exam Preparation @SoftUni</div>
</footer>


</body></html>